name: chat_app
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  dartz: ^0.10.1
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  logger: ^2.0.2+1
  meta: ^1.11.0
  mongo_dart: ^0.10.0

dev_dependencies:
  build_runner: ^2.4.8
 
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
